# Generated by Django 5.0.10 on 2025-01-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_module_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
