# Generated by Django 5.0.10 on 2025-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_is_paid_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
