# Generated by Django 5.0.10 on 2025-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
