# Generated by Django 5.0.10 on 2025-01-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_advertisement_alter_course_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='AD',
        ),
    ]
