# Generated by Django 5.0.10 on 2025-01-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enrollment_order_lesson_order_quiz_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='order',
        ),
    ]
