# Generated by Django 5.0.10 on 2025-01-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='owner',
        ),
    ]
