# Generated by Django 5.0.10 on 2025-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_enrollment_order_remove_lesson_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
