# Generated by Django 5.0.10 on 2025-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_enrollment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='order',
        ),
    ]
