# Generated by Django 5.0.10 on 2025-01-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
    ]
