# Generated by Django 5.0.10 on 2025-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lesson_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(null=True, verbose_name='Lesson Description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(null=True, verbose_name='Module Description'),
        ),
    ]
