# Generated by Django 5.0.10 on 2025-01-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lesson_description_alter_module_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
